spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KevynVillarraga/Springboot-config-kavq.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
         #search-locations: "file:///c:/SpringConfig"
server:
  port: 8071