spring:
  config:
    activate:
      on-profile: "qa"

# Property to be read from code
build:
  version: "v2.0"

#@ConfigurationProperties
contact:
  message: "Bank System - Account API"
  details:
    name: "Kavq - QA Tester Git Accounts"
    email: "Kavq@globalhitss.com"
  phone-numbers:
    -(57) 311-494-7050
    -(57) 300-245-0123